openapi: 3.2.0
info:
  version: '2022-10-28'
  x-release: v4
  title: AWS SimSpace Weaver Createsnapshot API
  description: SimSpace Weaver (SimSpace Weaver) is a managed service that you can use to build and operate large-scale spatial simulations in the Amazon Web Services Cloud.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: simspaceweaver
  x-aws-signingName: simspaceweaver
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/simspaceweaver-2022-10-28.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://simspaceweaver.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS SimSpace Weaver multi-region endpoint
- url: https://simspaceweaver.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS SimSpace Weaver multi-region endpoint
- url: http://simspaceweaver.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS SimSpace Weaver endpoint for China (Beijing) and China (Ningxia)
- url: https://simspaceweaver.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS SimSpace Weaver endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Createsnapshot
paths:
  /createsnapshot:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateSnapshot
      description: 'Creates a snapshot of the specified simulation. A snapshot is a file that contains simulation state data at a specific time. The state data saved in a snapshot includes entity data from the State Fabric, the simulation configuration specified in the schema, and the clock tick number. You can use the snapshot to initialize a new simulation. For more information about snapshots, see Snapshots in the SimSpace Weaver User Guide.


        You specify a Destination when you create a snapshot. The Destination is the name of an Amazon S3 bucket and an optional ObjectKeyPrefix. The ObjectKeyPrefix is usually the name of a folder in the bucket. SimSpace Weaver creates a snapshot folder inside the Destination and places the snapshot file there.


        The snapshot file is an Amazon S3 object. It has an object key with the form: object-key-prefix/snapshot/simulation-name-YYMMdd-HHmm-ss.zip, where:


        YY is the 2-digit year


        MM is the 2-digit month


        dd is the 2-digit day of the month


        HH is the 2-digit hour (24-hour clock)


        mm is the 2-digit minutes


        ss is the 2-digit seconds'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSnapshotOutput'
              examples:
                CreateSnapshot200Example:
                  summary: Default CreateSnapshot 200
                  x-microcks-default: true
                  value: {}
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
              examples:
                CreateSnapshot480Example:
                  summary: Default CreateSnapshot 480
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                CreateSnapshot481Example:
                  summary: Default CreateSnapshot 481
                  x-microcks-default: true
                  value: example-value
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                CreateSnapshot482Example:
                  summary: Default CreateSnapshot 482
                  x-microcks-default: true
                  value: example-value
        '483':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
              examples:
                CreateSnapshot483Example:
                  summary: Default CreateSnapshot 483
                  x-microcks-default: true
                  value: example-value
        '484':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                CreateSnapshot484Example:
                  summary: Default CreateSnapshot 484
                  x-microcks-default: true
                  value: example-value
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - Destination
              - Simulation
              properties:
                Destination:
                  description: An Amazon S3 bucket and optional folder (object key prefix) where SimSpace Weaver creates a file.
                  type: object
                  properties:
                    BucketName:
                      allOf:
                      - $ref: '#/components/schemas/BucketName'
                      - description: The name of an Amazon S3 bucket. For more information about buckets, see <a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/creating-buckets-s3.html">Creating, configuring, and working with Amazon S3 buckets</a> in the <i>Amazon Simple Storage Service User Guide</i>.
                    ObjectKeyPrefix:
                      allOf:
                      - $ref: '#/components/schemas/ObjectKeyPrefix'
                      - description: A string prefix for an Amazon S3 object key. It's usually a folder name. For more information about folders in Amazon S3, see <a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html">Organizing objects in the Amazon S3 console using folders</a> in the <i>Amazon Simple Storage Service User Guide</i>.
                Simulation:
                  description: The name of the simulation.
                  type: string
                  pattern: ^[a-zA-Z0-9_.-]+$
                  minLength: 1
                  maxLength: 64
            examples:
              CreateSnapshotRequestExample:
                summary: Default CreateSnapshot request
                x-microcks-default: true
                value:
                  Destination:
                    BucketName: MyResource
                    ObjectKeyPrefix: example-value
                  Simulation: example-value
      summary: Amazon Create Snapshot
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Createsnapshot
components:
  schemas:
    CreateSnapshotOutput:
      type: object
      properties: {}
    ValidationException: {}
    ObjectKeyPrefix:
      type: string
      minLength: 0
      maxLength: 1024
    BucketName:
      type: string
      minLength: 3
      maxLength: 63
    InternalServerException: {}
    ResourceNotFoundException: {}
    ConflictException: {}
    AccessDeniedException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/simspaceweaver/
x-hasEquivalentPaths: true
